version: "3.3"
services:
  db:
    image: mysql:8
    container_name: "mysql"
    restart: always
    privileged: true
    platform: linux/amd64
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nas
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nas
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - custom_net
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nas
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nas
    depends_on: 
      - db
    networks:
      - custom_net
  nginx:
    image: openresty/openresty:alpine
    container_name: "nginx"
    restart: always
    privileged: true
    volumes:
      - ./nginx/vhosts:/etc/nginx/conf.d
      - ./nginx/cert:/data/cert
      - ./nginx/logs:/data/logs
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - app
    networks:
      - custom_net
networks:
  custom_net:
    external:
      name: app_net  