version: "3.3"
services:
  nas-mysql:
    image: mysql:8
    container_name: "nas-mysql"
    restart: always
    privileged: true
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=Nas
      - MYSQL_PASSWORD=Nas
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nas
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - nas_net
  nextcloud:
#    image: nextcloud
    build: . 
    container_name: "nextcloud"
    restart: always
    privileged: true
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=Nas
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nas
    depends_on:
      - nas-mysql
      - nas-ftp
      - nas-redis
    networks:
      - nas_net
  nas-nginx:
    image: openresty/openresty:alpine
    container_name: "nas-nginx"
    restart: always
    privileged: true
    volumes:
      - ./nginx/vhosts:/etc/nginx/conf.d
      - ./nginx/cert:/data/cert
      - ./nginx/logs:/data/logs
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - nextcloud
    networks:
      - nas_net
  nas-ftp:
    image: fauria/vsftpd
    container_name: "nas-ftp"
    restart: always
    privileged: true
    environment:
      - FTP_USER=nas
      - FTP_PASS=Nas
      - PASV_ADDRESS=0.0.0.0
    volumes:
      - ./ftp:/home/vsftpd
    networks:
      - nas_net
  nas-redis:
    build: ./redis
    container_name: "nas-redis"
    restart: always
    privileged: true
    networks:
      - nas_net
networks:
  nas_net:
    external:
      name: nas_net